sudo: required
language: node_js
node_js:
- '9'
services:
- docker

before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
- yarn install

script:
- yarn test
- yarn build
- yarn build:docker
- docker tag justmaho/todo_client:latest registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script: docker push justmaho/todo_client; 
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:push web --app $HEROKU_APP_NAME;
    heroku container:release web --app $HEROKU_APP_NAME;
  on:
    branch: master
notifications:
  slack: justmaho:PWcuoJOJBreyeCP35p8PfDq9

addons:
  sonarcloud:
    organization: "justmaho-github"
    token:
      secure: "Z5fgJ+o2TH2q/GKIRGjotsxj1EwX6CJ/VCZ6DW1Twltqy/mCX1ySNOLZ7Fj7Wday2iqfR+cK3Gy5gjGg9FIhS4aM4ml4PUzNtfrWXdbZwBxiHkf8D6CIDk7HRAYORsuq+WzfsUbg8ZV6JdAih02o0HWsbaP2YjvplkvJpt5II8zk3KNtpPqUUDA5BisUJqBax5bwqbrazVPhKkQD5HmbziWSwQ13hNKyP03LND5LEStEhDZxNoc8pmwGRRMgzQzQFXPbSprospGC2LOhjGEvckiNcFYF/fNTEYKJqhSSvNgVYA1pyhIcWetkEqAMT5CQC54/Ve5Dp6NH9UmBfqpu04h5sk/uK+CazyhivJsTDsTrJxWqePIXkPOPNWfu8gSt5lcZQqFlgCDX1lbNK0cD8MbboLpzxv1IBCb+VwOx9eOwb0U/R7dTpwQElmL81sU5DfRlyBBn9o1oMQS6sQ2pX4bmm8rU8glnqYuTuUakPBRJfXc//l8OsH0K8RfgkYuniHVBqrijV5vfDVxauw13rMnyZzmL684bu34PJSMrdtKouyXCBGJmlZwHgkqCZMzvaDQutbNf5GcM9hQLZtNy1pO95gdwS2VZHqvscz6/m97HlZW5AKd4/LJgh0H+4e5F9Zrq06oy36h4ZTlCGQLdt0bqm5DgbLDytke39rv8AAs="
script:
  - sonar-scanner